# This workflow is used to build a Debian package for multiple Debian releases

name: Build Package

# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
    workflow_dispatch:

jobs:
  build-package:
    uses: centic9/actions/.github/workflows/debian-package.yml@9
